---
image: ghcr.io/joejcollins/lady-penelope:latest

tasks:
  - name: R and Python setup
    before: | # Preparatory steps that should run before the main setup, such as setting up tools.
      sudo chown -R rstudio:rstudio /workspace
    init: | # Tasks for setting up the project, like downloading dependencies.
      make venv
    command: | # Commands that start your main application or services.
      sudo chown -R rstudio:rstudio /workspace
      sudo su - rstudio

ports:
  - name: Rstudio
    port: 8787
    onOpen: open-browser
  - name: Jupyter
    port: 8888
    onOpen: open-browser

vscode:
  extensions:
    - charliermarsh.ruff
    - ms-azuretools.vscode-docker
    - charliermarsh.ruff
    - eamodio.gitlens
    - james-yu.latex-workshop
    - ms-python.black-formatter
    - ms-python.mypy-type-checker
    - ms-python.python
    - RDebugger.r-debugger
    - reditorsupport.r
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
...