---
name: Build Python Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-python-docker-image.yml'
      - 'requirements.txt'
      - '.devcontainer/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout the repo to depth of 2 so we can see what has changed (if needed).
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
        submodules: false
        clean: true

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set short git commit SHA
      run: |
        calculatedSha=$(git rev-parse --short ${{ github.sha }})
        echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

    - name: Build and Push Python Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./.devcontainer/Dockerfile
        push: true
        tags: |
          ghcr.io/joejcollins/lady-penelope-python:latest
          ghcr.io/joejcollins/lady-penelope-python:${{ env.COMMIT_SHORT_SHA }}
...