---
name: Run All Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/lady-penelope:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        clean: true

    - name: Symlink the prebuilt assets and run tests.
      run: |
        ln -snf /app/.venv .venv
        .venv/bin/python -m pip install --editable .
        ln -snf /app/.R .R
        make test